/**
 * Regenerate src/client/assets.ts from the raw clips in assets/.
 * Run `npm run embed-audio` after replacing assets/mama.mp3 or
 * assets/niulai.mp3, then `npm run build` to refresh lib/client.js.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

const CLIPS = [
  ['MAMA_DEFAULT', '妈妈.mp3'],
  ['NIULAI_DEFAULT', '牛来.mp3'],
]

const body = CLIPS.map(([name, file]) => {
  const data = readFileSync(join(root, 'assets', file)).toString('base64')
  return `export const ${name} = 'data:audio/mpeg;base64,${data}'`
}).join('\n\n')

const header = `/**
 * Embedded default sound clips for the niu-lai sound board.
 * Generated by scripts/embed-audio.mjs from assets/ — do not edit by hand.
 */\n\n`

writeFileSync(join(root, 'src', 'client', 'assets.ts'), `${header}${body}\n`)
console.log('embedded assets/ → src/client/assets.ts')
